### ISSUE TITLE
forEach?

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code-Examples-p5.js#17]
This is relevant for particle system examples and anything that has an array really.  I've been looping through arrays with a for loop:

```
for (var i = 0; i < particles.length; i++) {
  particles[i].update();
  particles[i].display();
}
```

But am considering using [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach).

```
var go = function(particle) {
    particle.update();
    particle.display(); 
}
particles.forEach(go);
```

and this can be written with an anonymous function, like so:

```
particles.forEach(function(particle) {
  particle.update();
  particle.display();   
});
```

I am thinking about the following questions:
- What is best for beginners?
- What is the JS convention?
- Does this play a role in teaching functional programming / closures?
- What ultimately will be most concise / readable?

Maybe this is simple and I am overthinking it.  . .and the answer is just always use a for loop, but curious what folks might have thoughts in terms of approaches for teaching arrays in p5.js.

@pamelafox @lmccart @reas @evhan55 @brysonian

**Comment by xpluscal** [comment]
Is there any news on this topic?
Thanks!
