### ISSUE TITLE
Ch. 2 Lesson 4 sketch.js - .get() not a function

### ISSUE THREAD

**Issue by jefarrell** [shiffman/The-Nature-of-Code-Examples-p5.js#30]
Line 24 of forces & friction example:
`var friction = movers[i].velocity.get();`

.get() is not a function - mistaken leftover from Processing port?

**Comment by shiffman** [comment]
ah, yes it should be `copy()` I think?

**Comment by jefarrell** [comment]
Yep that did it - I found a couple other minor issues so far, I'll submit pull requests shortly.

**Comment by shiffman** [comment]
Fantastic!  I'll leave this open until fixed in the repo.  Thank you!

**Comment by extrasleepy** [comment]
Funny thing: var friction = movers[i].velocity.copy(); did not work when I tested in Chrome, but .get() did!!!

**Comment by shiffman** [comment]
I updated the p5 version for all examples and switched `get()` to `copy()`.  I might have missed something but hopefully all are working now!
