### ISSUE TITLE
NOC_7_01_WolframCA_simple potential bug

### ISSUE THREAD

**Issue by cdaein** [shiffman/The-Nature-of-Code-Examples-p5.js#38]
Hi, Dan
While following the example, I found a potential bug.

```javascript
this.generate = function() {
    // First we create an empty array for the new values
    var nextgen = new Array(this.cells.length);
    // For every spot, determine new state by examing current state, and neighbor states
    // Ignore edges that only have one neighor
    for (var i = 1; i < this.cells.length-1; i++) {
      var left   = this.cells[i-1];   // Left neighbor state
      var me     = this.cells[i];     // Current state
      var right  = this.cells[i+1];   // Right neighbor state
      nextgen[i] = this.rules(left, me, right); // Compute next generation state based on ruleset
    }
    // The current generation is the new generation
    this.cells = nextgen;
    this.generation++;
  };
```

In the above code, `var nextgen` gets the length when it's created, but the initializing is done through a for loop, which starts at `i = 1`, therefore, leaving `nextgen[0]` undefined. In this particular example, it works fine because `this.rules` function returns `0` as default, but when I was implementing another version of `this.rules` function, it caused me a problem.

I am not an expert in Javascript, but changing as below fixed the issue for me:

```javascript
 var nextgen = new Array(this.cells.length);
 for (var i = 0; i < nextgen.length; i++) {
  nextgen[i] = 0;
 }
```

**Comment by shiffman** [comment]
Ah, this is indeed a bug!   Thanks, fixed now!
