### ISSUE TITLE
9.05 Ecosystem world.js - after a bloop dies

### ISSUE THREAD

**Issue by cdaein** [shiffman/The-Nature-of-Code-Examples-p5.js#39]
Hi, Dan

After running this example for a while, it causes an error:
`Uncaught TypeError: undefined is not a function` at world.js:43

world.js line 43 is:
`this.food.push(b.location);`

it should be
`this.food.add(b.location);`

I think you were confused with ArrayList add(), which translates to push(), and the actual add() method of Food object.

Also on the same line,
`b.location` should be `b.position` as it is how it's defined in bloops.js

**Comment by shiffman** [comment]
Thanks for these corrections!
